apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  ports:
  - port: 31000
    nodePort: 31000
    targetPort: nginx-port
    protocol: TCP
  selector:
    app: my-angular
  type: NodePort
